/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExampleRouteImport } from './routes/example'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayForm1RouteImport } from './routes/play.form1'
import { Route as PlayFormRouteImport } from './routes/play.form'

const ExampleRoute = ExampleRouteImport.update({
  id: '/example',
  path: '/example',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayForm1Route = PlayForm1RouteImport.update({
  id: '/play/form1',
  path: '/play/form1',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayFormRoute = PlayFormRouteImport.update({
  id: '/play/form',
  path: '/play/form',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/example': typeof ExampleRoute
  '/play/form': typeof PlayFormRoute
  '/play/form1': typeof PlayForm1Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/example': typeof ExampleRoute
  '/play/form': typeof PlayFormRoute
  '/play/form1': typeof PlayForm1Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/example': typeof ExampleRoute
  '/play/form': typeof PlayFormRoute
  '/play/form1': typeof PlayForm1Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/example' | '/play/form' | '/play/form1'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/example' | '/play/form' | '/play/form1'
  id: '__root__' | '/' | '/example' | '/play/form' | '/play/form1'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExampleRoute: typeof ExampleRoute
  PlayFormRoute: typeof PlayFormRoute
  PlayForm1Route: typeof PlayForm1Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/example': {
      id: '/example'
      path: '/example'
      fullPath: '/example'
      preLoaderRoute: typeof ExampleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/form1': {
      id: '/play/form1'
      path: '/play/form1'
      fullPath: '/play/form1'
      preLoaderRoute: typeof PlayForm1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/form': {
      id: '/play/form'
      path: '/play/form'
      fullPath: '/play/form'
      preLoaderRoute: typeof PlayFormRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExampleRoute: ExampleRoute,
  PlayFormRoute: PlayFormRoute,
  PlayForm1Route: PlayForm1Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
