/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutForm2RouteImport } from './routes/_layout.form2'
import { Route as LayoutForm1RouteImport } from './routes/_layout.form1'
import { Route as LayoutFormRouteImport } from './routes/_layout.form'
import { Route as LayoutExampleRouteImport } from './routes/_layout.example'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutForm2Route = LayoutForm2RouteImport.update({
  id: '/form2',
  path: '/form2',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutForm1Route = LayoutForm1RouteImport.update({
  id: '/form1',
  path: '/form1',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFormRoute = LayoutFormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExampleRoute = LayoutExampleRouteImport.update({
  id: '/example',
  path: '/example',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/example': typeof LayoutExampleRoute
  '/form': typeof LayoutFormRoute
  '/form1': typeof LayoutForm1Route
  '/form2': typeof LayoutForm2Route
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesByTo {
  '/example': typeof LayoutExampleRoute
  '/form': typeof LayoutFormRoute
  '/form1': typeof LayoutForm1Route
  '/form2': typeof LayoutForm2Route
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/example': typeof LayoutExampleRoute
  '/_layout/form': typeof LayoutFormRoute
  '/_layout/form1': typeof LayoutForm1Route
  '/_layout/form2': typeof LayoutForm2Route
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/example' | '/form' | '/form1' | '/form2' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/example' | '/form' | '/form1' | '/form2' | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/example'
    | '/_layout/form'
    | '/_layout/form1'
    | '/_layout/form2'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/form2': {
      id: '/_layout/form2'
      path: '/form2'
      fullPath: '/form2'
      preLoaderRoute: typeof LayoutForm2RouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/form1': {
      id: '/_layout/form1'
      path: '/form1'
      fullPath: '/form1'
      preLoaderRoute: typeof LayoutForm1RouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/form': {
      id: '/_layout/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof LayoutFormRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/example': {
      id: '/_layout/example'
      path: '/example'
      fullPath: '/example'
      preLoaderRoute: typeof LayoutExampleRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutExampleRoute: typeof LayoutExampleRoute
  LayoutFormRoute: typeof LayoutFormRoute
  LayoutForm1Route: typeof LayoutForm1Route
  LayoutForm2Route: typeof LayoutForm2Route
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutExampleRoute: LayoutExampleRoute,
  LayoutFormRoute: LayoutFormRoute,
  LayoutForm1Route: LayoutForm1Route,
  LayoutForm2Route: LayoutForm2Route,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
